"""m18

Revision ID: 1349a6fd4aa0
Revises: 602738143b77
Create Date: 2025-03-24 18:02:27.951740

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1349a6fd4aa0'
down_revision = '602738143b77'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('search_marker')
    with op.batch_alter_table('work_markers', schema=None) as batch_op:
        batch_op.drop_constraint('work_markers_marker_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('work_markers_work_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'search_markers', ['marker_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'works', ['work_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_constraint('works_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('works_user_id_fkey', 'users', ['user_id'], ['id'])

    with op.batch_alter_table('work_markers', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('work_markers_work_id_fkey', 'works', ['work_id'], ['id'])
        batch_op.create_foreign_key('work_markers_marker_id_fkey', 'search_markers', ['marker_id'], ['id'])

    op.create_table('search_marker',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='search_marker_pkey'),
    sa.UniqueConstraint('name', name='search_marker_name_key')
    )
    # ### end Alembic commands ###
