"""m13

Revision ID: 69232e84e932
Revises: 914cbfe35f1d
Create Date: 2025-03-22 16:49:00.395585

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69232e84e932'
down_revision = '914cbfe35f1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_url', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.drop_column('video_url')

    # ### end Alembic commands ###
