"""m4

Revision ID: 9768284b2949
Revises: 
Create Date: 2025-03-16 13:16:08.760370

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9768284b2949'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('search_markers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name', sa.String(length=100), nullable=False))
        batch_op.create_unique_constraint(None, ['name'])
        batch_op.drop_constraint('search_markers_work_id_fkey', type_='foreignkey')
        batch_op.drop_column('work_id')
        batch_op.drop_column('marker')

    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_published', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('category', sa.String(length=50), nullable=True))
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('works', schema=None) as batch_op:
        batch_op.alter_column('description',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.drop_column('category')
        batch_op.drop_column('is_published')

    with op.batch_alter_table('search_markers', schema=None) as batch_op:
        batch_op.add_column(sa.Column('marker', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('work_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.create_foreign_key('search_markers_work_id_fkey', 'works', ['work_id'], ['id'])
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('name')

    # ### end Alembic commands ###
